version: '3'

services:
        node:
                build: ./node
                ports:
                        - "4000:4000"
                depends_on:
                        - mysql
                restart: always
                environment:
                        - DATABASE_HOST=mysql
                volumes:
                        - ./node:/app
        mysql:
                build: ./database
                ports:
                        - "3306:3306"
