version: '3'

services:
  node:
    container_name: app
    build: ./node
    restart: always
    ports:
      - "4000:4000"
    depends_on:
     - mysqldb
    environment:
     - DATABASE_HOST=mysqldb
    volumes:
     - ./node:/usr/src/app
  mysqldb:
    container_name: mysqldb
    build: ./database
    restart: always
    ports:
      - "3306:3306"